name: flutter_tui
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  uuid: ^4.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
